name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    env:
      VITE_EMAIL_JS_PUBLIC_KEY: ${{ secrets.VITE_EMAIL_JS_PUBLIC_KEY }}
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install all dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
